package dog.snow.androidrecruittest.utils

object JsonLabels {
    const val UNKNOWN = "unknown"
    const val STREET = "street"
    const val SUITE = "suite"
    const val CITY = "city"
    const val ZIPCODE = "zipcode"
    const val GEO = "geo"
    const val ID = "id"
    const val USERID = "userId"
    const val TITLE = "title"
    const val NAME = "name"
    const val CATCHPHRASE = "catchPhrase"
    const val BS = "bs"
    const val LAT = "lat"
    const val LNG = "lng"
    const val ALBUMID = "albumId"
    const val URL = "url"
    const val THUMBNAILURL = "thumbnailUrl"
    const val EMAIL = "email"
    const val USERNAME = "username"
    const val ADDRESS = "address"
    const val PHONE = "phone"
    const val WEBSITE = "website"
    const val COMPANY = "company"
}